---
- name: Verify that required vars are defined and populated
  include_role:
    name: mstansberry.ansible_rancher.required_vars
  vars:
    required_vars:
      - rancher_server_url
      - api_token

- name: Get current Global Roles
  mstansberry.ansible_rancher.rancher_list:
    rancher_url: "{{ rancher_server_url }}"
    token: "{{ api_token }}"
    cluster_name: "{{ cluster_name|default(omit) }}"
    target_type: globalRole
  register: rancher_list_global_role
  delegate_to: localhost

- name: Get current Role Templates
  mstansberry.ansible_rancher.rancher_list:
    rancher_url: "{{ rancher_server_url }}"
    token: "{{ api_token }}"
    cluster_name: "{{ cluster_name|default(omit) }}"
    target_type: roleTemplate
  register: rancher_list_role_template
  delegate_to: localhost
