---
- name: Verify that required vars are defined and populated
  include_role:
    name: mstansberry.ansible_rancher.required_vars
  vars:
    required_vars:
      - rancher_server_url
      - api_token
      - rbac_role_templates

- name: Create Global Role Templates
  mstansberry.ansible_rancher.rancher_global_role:
    rancher_url: "{{ rancher_server_url }}"
    token: "{{ api_token }}"
    global_role_name: "{{ item.name }}"
    global_role_config: "{{ item }}"
  delegate_to: localhost
  with_items: "{{ rbac_role_templates['global'] }}"
  when: '"global" in rbac_role_templates'

- name: Create Cluster Role Templates
  mstansberry.ansible_rancher.rancher_role_template:
    rancher_url: "{{ rancher_server_url }}"
    token: "{{ api_token }}"
    role_template_name: "{{ item.name }}"
    role_template_config: "{{ item }}"
  delegate_to: localhost
  with_items: "{{ rbac_role_templates['cluster'] }}"
  when: '"cluster" in rbac_role_templates'

- name: Create Project Role Templates
  mstansberry.ansible_rancher.rancher_role_template:
    rancher_url: "{{ rancher_server_url }}"
    token: "{{ api_token }}"
    role_template_name: "{{ item.name }}"
    role_template_config: "{{ item }}"
  delegate_to: localhost
  with_items: "{{ rbac_role_templates['project'] }}"
  when: '"project" in rbac_role_templates'
